# /// script
# requires-python = ">=3.11"
# dependencies = ["requests>=2.31"]
# ///
"""Pull the two third-party runtime dependencies into the tree.

The guide has to work with no network at all — a visitor holding a phone in a
gallery basement is the design target — so `justif` and the two typefaces are
vendored rather than loaded from a CDN. Both are fetched at pinned versions and
committed, which keeps the page a plain static file with no build step.
"""

from __future__ import annotations

import argparse
import posixpath
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import ASSETS, ROOT, Fetcher  # noqa: E402

JUSTIF_VERSION = "0.8.0"
JUSTIF_CDN = f"https://cdn.jsdelivr.net/npm/justif@{JUSTIF_VERSION}/dist"
JUSTIF_ENTRIES = ["index.js", "hyphenate/en-us.js"]
VENDOR = ROOT / "vendor" / "justif"

# Matches the module specifier of any relative import/export in an ES module,
# under either quote style, including bare `import './x.js'` side-effect forms.
RELATIVE_IMPORT = re.compile(r"""(?:from|import)\s*['"](\.{1,2}/[^'"]+)['"]""")

# Cormorant SC is a separate family, not a feature of Cormorant Garamond: the
# Garamond webfont carries no `smcp` table, so `font-variant-caps` would only
# get the browser's synthesised shrunken capitals.
GOOGLE_FONTS = (
    "https://fonts.googleapis.com/css2"
    "?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,400"
    "&family=Cormorant+SC:wght@400;600"
    "&family=Lora:ital,wght@0,400;0,500;0,600;1,400&display=swap"
)
# Chrome's UA makes the API answer with woff2 rather than the legacy formats.
WOFF2_UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0 Safari/537.36")
FONTS = ASSETS / "fonts"
# The guide is English over Dutch names; the other subsets Google ships would
# more than double the vendored weight for glyphs the copy never reaches for.
WANTED_SUBSETS = ("latin", "latin-ext")


def vendor_justif(fetcher: Fetcher) -> None:
    """Fetch the entry points and every relative module they reach, transitively."""
    pending, seen = list(JUSTIF_ENTRIES), set()

    while pending:
        relative = pending.pop()

        if relative in seen:
            continue

        seen.add(relative)
        source = fetcher.get_bytes(f"{JUSTIF_CDN}/{relative}", suffix=".js").decode()

        destination = VENDOR / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(source)

        base = posixpath.dirname(relative)
        pending += [posixpath.normpath(posixpath.join(base, specifier))
                    for specifier in RELATIVE_IMPORT.findall(source)]

    for orphan in VENDOR.rglob("*"):
        if orphan.is_file() and orphan.relative_to(VENDOR).as_posix() not in seen:
            orphan.unlink()

    print(f"vendored {len(seen)} justif modules at {JUSTIF_VERSION}", file=sys.stderr)


def vendor_fonts(fetcher: Fetcher) -> None:
    """Download the Google Fonts stylesheet and rewrite it to local woff2 files."""
    FONTS.mkdir(parents=True, exist_ok=True)
    stylesheet = fetcher.session.get(GOOGLE_FONTS, headers={"User-Agent": WOFF2_UA},
                                     timeout=60)
    stylesheet.raise_for_status()
    # Google Fonts labels each @font-face with the subset it covers; keep only ours.
    blocks = re.split(r"(?=/\* [a-z-]+ \*/)", stylesheet.text)
    css = "".join(block for block in blocks
                  if not block.startswith("/*")
                  or block.split("*/")[0].strip("/* ") in WANTED_SUBSETS)

    for url in sorted(set(re.findall(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", css))):
        name = url.rsplit("/", 1)[-1]
        (FONTS / name).write_bytes(fetcher.get_bytes(url, suffix=".woff2"))
        css = css.replace(url, name)

    (FONTS / "fonts.css").write_text(
        "/* Generated by tools/vendor.py from Google Fonts. Do not edit. */\n" + css)
    print(f"vendored {len(list(FONTS.glob('*.woff2')))} font files", file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="ignore the HTTP cache")
    args = parser.parse_args()

    fetcher = Fetcher("vendor", force=args.force)
    vendor_justif(fetcher)
    vendor_fonts(fetcher)


if __name__ == "__main__":
    main()
